version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/wayspeak
      - MONGO_DB_NAME=wayspeak
      - REDIS_URL=redis://redis:6379
      - WHATSAPP_API_KEY=${WHATSAPP_API_KEY}
      - WHATSAPP_API_URL=${WHATSAPP_API_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
